runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: src/\1
    upload: src/(.*)(|\.map)

  - url: /(.*)
    static_files: src/index.html
    upload: src/index.html
